#!/bin/bash

#// delve debugeris
go get -u github.com/derekparker/delve/cmd/dlv

#// komandas
go get -u golang.org/x/tools/...

#// no atoma
#// 1)
go get -u golang.org/x/tools/cmd/...
go get -u golang.org/x/lint/golint

#// 2)
go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/gorename
go get -u github.com/sqs/goreturns
#go get -u github.com/nsf/gocode
go get -u github.com/mdempsky/gocode
go get -u github.com/alecthomas/gometalinter
go get -u github.com/zmb3/gogetdoc
go get -u github.com/rogpeppe/godef
go get -u golang.org/x/tools/cmd/guru

#// no golanga
#// tikai derīgais saraksts
go get -u golang.org/x/tools/cmd/godoc

#// šitas no sublimes
#go get -u golang.org/x/tools/cmd/vet		šitas jau ir defaulti golanga valodas download'ā
#go get -u golang.org/x/tools/cmd/oracle         vecs, tā vietā tagad guru

#// vscode
go get -u github.com/tpng/gopkgs
go get -u github.com/lukehoban/go-outline
go get -u github.com/uudashr/gopkgs/cmd/gopkgs

#// vscode prasīja analīzei
#Installing github.com/acroca/go-symbols SUCCEEDED
#Installing github.com/fatih/gomodifytags SUCCEEDED
#Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
#Installing github.com/josharian/impl SUCCEEDED
#Installing github.com/cweill/gotests/... SUCCEEDED

