#!/bin/bash

echo "Vajag salabot PointCmdBite (tas par lielu priekš RASPBERIJA)"

# golang itself
GO_DL_PC="https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz"
GO_DL_RASP="https://dl.google.com/go/go1.12.9.linux-armv6l.tar.gz"
GO_DL=$GO_DL_RASP
#GO_DIR=$HOME/Tools/dev
GO_DIR=$HOME/Tools/dev1234
GO_LANG_GZ="go-dl.tar.gz"

# application code
GO_DEV_BASE=$HOME/0_Dev/
GO_DEV_DIR="goArduino"
GO_DEV_GO_DIR="go"
GIT_URL_BITBUCKET="git@bitbucket.org:vilishens/next.git"
GIT_URL_GITHUB_BASE="https://github.com/vilishens/goPrototipsBase.git"
GIT_URL_BASE=$GIT_URL_GITHUB_BASE
GIT_URL_GITHUB_GO="https://github.com/vilishens/goPrototipsGo.git"
GIT_URL_GO=$GIT_URL_GITHUB_GO

# environment settings
GO_ROOT=$GO_DIR/go
GO_PATH=$GO_DEV_BASE$GO_DEV_DIR/$GO_DEV_GO_DIR

# temporary environment settings
GO_PATH_TMP=$HOME/0_Dev/go_temporary

