#!/bin/bash

BACK_DIR=$1
GO_ROOT=$2
GO_PATH=$3
SENDGRID_KEY=$4

echo ' '
echo 'export GOROOT='$GO_ROOT >> $HOME/.profile
echo 'export GOPATH='$GO_PATH >> $HOME/.profile
echo 'export PATH=$PATH:$GOROOT'/bin >> $HOME/.profile

# return to the start directory
cd $BACK_DIR

exit 12
